# Initializes a new nodejs project with docker

version: '3.7'
services:
  graphql:
    image: node:16.13.2-alpine
    container_name: graphql
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - graphql-redis
    command: sh -c "npm i && npm start"
    ports:
      - '5000:5000'
    volumes:
      - ./:/var/www
    networks:
      - graphql

  graphql-redis:
    image: redis:alpine
    container_name: graphql-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - graphql

networks:
  graphql:
    driver: bridge
