# Initializes a new nodejs project with docker

version: '3.7'
services:
  app:
    image: node:16.13.2-alpine
    container_name: graphql
    restart: unless-stopped
    working_dir: /var/www
    command: sh -c "npm i && npm start"
    ports:
      - '5000:5000'
    volumes:
      - ./:/var/www
    networks:
      - app

networks:
  app:
    driver: bridge
