# Initializes a new nodejs project with docker

version: '3.7'
services:
  graphql-api:
    depends_on:
      - graphql-redis
      - graphql-database
    build:
      args:
        user: graphql
        uid: 9999
      context: ./
      dockerfile: Dockerfile
    image: graphql-api
    container_name: graphql-api
    restart: unless-stopped
    working_dir: /var/www
    command: sh -c "npm i --no-audit && npm start"
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/var/www
    networks:
      - graphql

  graphql-database:
    image: mysql:8.0
    container_name: graphql-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./storage/mysql:/var/lib/mysql
    networks:
      - graphql

  graphql-redis:
    image: redis:alpine
    container_name: graphql-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./storage/redis:/var/lib/redis
    networks:
      - graphql

networks:
  graphql:
    driver: bridge
